### ISSUE TITLE
Third party loggers

### ISSUE THREAD

**Issue by jyounus** [tadija/AEConsole#2]
Hey,

Can I use this with my custom logging solution? Is there maybe a protocol available to implement and pass the object into AEConsole?

Thanks!

**Comment by tadija** [comment]
Hi, unfortunately that's not possible at the moment (it works just with AELog currently), but it's a good idea for the future, thanks. :)

**Comment by jyounus** [comment]
I'm definitely looking forward to it! Would be great to have that. 

Thanks :D

**Comment by tadija** [comment]
Hey @jyounus, better late then never, but this is now added in the latest 0.5.0 version... :)

It was quite easy actually, I just replaced `Line` type from `AELog` to `CustomStringConvertible` and added API for that.

Thanks for the idea!
