### ISSUE TITLE
Ho to manually export log to file

### ISSUE THREAD

**Issue by olivier38070** [tadija/AEConsole#3]
Hi,

there is a button, in AECOnsole, to export logs values, to a file, in document app folder.

how can I do that by code (swift, if possible) ?

I don't know how to contact you, so I posted a issue,

sorry for that

thanks
Olivier

**Comment by tadija** [comment]
Hi @olivier38070, this is now added in the latest 0.5.0 version and you can export log file with calling `Console.shared.exportLogFile()`.
